# Form implementation generated from reading ui file 'verflixxt_pfiffiges_tool.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os

def resource_path(relative_path):
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 600)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("TeXGyreAdventor")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_Florentin = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_Florentin.setFont(font)
        self.lineEdit_Florentin.setObjectName("lineEdit_Florentin")
        self.gridLayout.addWidget(self.lineEdit_Florentin, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("TeXGyreAdventor")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_Lars = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_Lars.setFont(font)
        self.lineEdit_Lars.setObjectName("lineEdit_Lars")
        self.gridLayout.addWidget(self.lineEdit_Lars, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("TeXGyreAdventor")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_result = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_result.setFont(font)
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.gridLayout.addWidget(self.lineEdit_result, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("TeXGyreAdventor")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        
        # connect signal
        self.pushButton.clicked.connect(self.determine_winner)

        self.verticalLayout.addWidget(self.pushButton)
        self.label_result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("TeXGyreAdventor")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(resource_path("images/Florentin_pic.jpeg")))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(resource_path("images/geier.jpeg")))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(resource_path("images/Waller.jpeg")))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(resource_path("images/Lars_pic.jpeg")))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Verflixxt Pfiffiges Tool"))
        self.label.setText(_translate("Form", "Florentin\'s Schätzung"))
        self.label_2.setText(_translate("Form", "Lars\' Schätzung"))
        self.label_3.setText(_translate("Form", "tatsächlicher Preis/Clickzahl"))
        self.pushButton.setText(_translate("Form", "bestimme Sieger"))

    def determine_winner(self):
            estimate_Lars = int(self.lineEdit_Lars.text())
            estimate_Florentin = int(self.lineEdit_Florentin.text())
            true_result = int(self.lineEdit_result.text())

            if(abs(estimate_Lars-true_result)>abs(estimate_Florentin-true_result)):
                self.label_result.setText("Lars hat sich um {} verschätzt"\
                    "und Florentin nur um {}\nFlorentin gewinnt"\
                        .format(abs(estimate_Lars-true_result),\
                            abs(estimate_Florentin-true_result)))
            
            elif(abs(estimate_Lars-true_result)<abs(estimate_Florentin-true_result)):
                self.label_result.setText("Florentin hat sich um {} verschätzt"\
                    "und Lars nur um {}\nLars gewinnt"\
                        .format(abs(estimate_Florentin-true_result),
                        abs(estimate_Lars-true_result)))
            else:
                self.label_result.setText("Beide haben gleich gut geschätzt :)")
            if(abs(estimate_Lars-true_result)==0):
                self.label_result.setText("Direkter Treffer von Lars!!!")
            if(abs(estimate_Florentin-true_result)==0):
                self.label_result.setText("Direkter Treffer von Florentin")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
